"""empty message

Revision ID: 233aebadef3a
Revises: 3cf92acdd4e7
Create Date: 2024-01-29 16:42:24.907852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233aebadef3a'
down_revision = '3cf92acdd4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('other_savings')
        batch_op.drop_column('account_number')
        batch_op.drop_column('state')
        batch_op.drop_column('gender')
        batch_op.drop_column('photo')
        batch_op.drop_column('isa_savings')
        batch_op.drop_column('premier_account')
        batch_op.drop_column('account_status')
        batch_op.drop_column('transaction_pin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_pin', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('premier_account', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('isa_savings', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=1000000), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=400), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('other_savings', sa.VARCHAR(length=400), nullable=True))

    # ### end Alembic commands ###
