"""empty message

Revision ID: 25df1b1850e1
Revises: 233aebadef3a
Create Date: 2024-01-29 17:41:49.439275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25df1b1850e1'
down_revision = '233aebadef3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=255), nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
