"""empty message

Revision ID: 3cf92acdd4e7
Revises: 
Create Date: 2023-10-11 11:56:41.150638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf92acdd4e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('id_upload',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('messager', schema=None) as batch_op:
        batch_op.alter_column('info',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('Payment_status',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('room_type', schema=None) as batch_op:
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('base_occupancy',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('extral_bed_price',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('kids_occupancy',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('base_price',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('amenities',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('image_one',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('image_two',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('image_three',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_number',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('reserved',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('image_one',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('occupied_by',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('occupied_state',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('occupied_state',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('occupied_by',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('image_one',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('reserved',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('room_type',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('room_number',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('room_type', schema=None) as batch_op:
        batch_op.alter_column('image_three',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('image_two',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('image_one',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('amenities',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('base_price',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('kids_occupancy',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('extral_bed_price',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('base_occupancy',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('room_type',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('Payment_status',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('messager', schema=None) as batch_op:
        batch_op.alter_column('info',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('id_upload',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    # ### end Alembic commands ###
