"""empty message

Revision ID: 887ef792a34e
Revises: d6bb5f26bc85
Create Date: 2024-02-09 16:18:54.658632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887ef792a34e'
down_revision = 'd6bb5f26bc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
