"""empty message

Revision ID: d2d390c0c995
Revises: 4b178a766bc2
Create Date: 2024-11-22 17:56:59.432666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d390c0c995'
down_revision = '4b178a766bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('has_checkout', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'guests', ['guest_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'guests', ['guest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('guest_id')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('has_checkout')
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
