"""empty message

Revision ID: ed0feee4f467
Revises: d2d390c0c995
Create Date: 2024-12-08 23:14:39.105845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0feee4f467'
down_revision = 'd2d390c0c995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('family', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemi', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('family')
        batch_op.drop_column('Category')

    # ### end Alembic commands ###
