"""empty message

Revision ID: ee53a895e369
Revises: 887ef792a34e
Create Date: 2024-02-09 16:28:24.364035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee53a895e369'
down_revision = '887ef792a34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.VARCHAR(length=400), nullable=True))

    # ### end Alembic commands ###
