"""empty message

Revision ID: ee9a8b8cbba7
Revises: 5263d2e79447
Create Date: 2024-02-11 15:00:17.806079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9a8b8cbba7'
down_revision = '5263d2e79447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('task', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('task')
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###
